version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Zipping frontend files..."
      - zip -r frontend.zip . -x "*.git*"
      - echo "Zipping lambda files..."
      - zip -r lambda.zip lambda/
  post_build:
    commands:
      - echo "Uploading frontend to S3..."
      - aws s3 cp frontend.zip s3://aitechie-codepipeline-artifacts/
      - echo "Uploading Lambda functions to S3..."
      - aws s3 cp lambda.zip s3://aitechie-codepipeline-artifacts/

artifacts:
  files:
    - frontend.zip
    - lambda.zip
    - appspec.yml
    - scripts/*
