version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Python runtime for AWS CLI
    commands:
      - echo "Installing AWS CLI..."
      - pip install awscli --upgrade  # Ensure AWS CLI is installed and up-to-date

      - echo "Installing dependencies..."
      - sudo apt-get update  # Update package list
      - sudo apt-get install -y zip unzip  # Install zip/unzip utilities

  pre_build:
    commands:
      - echo "Preparing build environment..."
      - echo "AWS CLI version:"
      - aws --version  # Verify AWS CLI installation

  build:
    commands:
      - echo "Building application..."
      # Add any build commands here (e.g., npm install, npm run build)
      - echo "No build step required for static files."

  post_build:
    commands:
      - echo "Preparing artifacts for deployment..."
      - zip -r build.zip . -x "*.git*" "
