version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Python runtime for AWS CLI
    commands:
      - echo "Installing AWS CLI..."
      - pip install awscli --upgrade  # Ensure AWS CLI is installed and up-to-date

      - echo "Installing dependencies..."
      - echo "Checking package manager..."
      - if command -v yum &> /dev/null; then
          echo "Using yum (Amazon Linux 2)...";
          yum update -y && yum install -y zip unzip;
        elif command -v dnf &> /dev/null; then
          echo "Using dnf (Amazon Linux 2023)...";
          dnf update -y && dnf install -y zip unzip;
        else
          echo "Unsupported package manager. Exiting...";
          exit 1;
        fi

      - echo "Installed dependencies:"
      - zip --version
      - unzip --version

  pre_build:
    commands:
      - echo "Preparing build environment..."
      - echo "AWS CLI version:"
      - aws --version  # Verify AWS CLI installation

      - echo "Current directory:"
      - pwd
      - echo "Listing files:"
      - ls -l

  build:
    commands:
      - echo "Building application..."
      - echo "No build step required for static files."

  post_build:
    commands:
      - echo "Preparing artifacts for deployment..."
      - mkdir -p artifacts  # Create an artifacts directory

      - echo "Copying static files (HTML, CSS, JS) to artifacts directory..."
      - cp -r css js *.html artifacts/

      - echo "Copying Lambda ZIP files to artifacts directory..."
      - cp -r lambda/*.zip artifacts/lambda/

      - echo "Zipping the artifacts for deployment..."
      - cd artifacts
      - zip -r ../build.zip .  # Create a build.zip file
      - cd ..

      - echo "Uploading artifacts to S3..."
      - aws s3 cp build.zip s3://my-web-app-bucket/build.zip  # Upload to S3

artifacts:
  files:
    - 'build.zip'  # The artifact to be uploaded to S3
  discard-paths: no
